# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0aa454683297cce00f017a39fcaa9744716aa4fe7cdb196665e61aea74dc47ee3c37819c7ed9da9a8030436b2847f82073deaa1f5a1cbcf94e72925ac3da75f6

test:
  secret_key_base: 587509f72c506850f6941e0fbc3897d4da4ba4af548c0be39d390e49217806e439e43cbed6b38a3f1db237949ec6eb905be1c57002006a5773dda0136337e0e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
